name: Friday_Final_Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Buildozer
        uses: ArtemGr/buildozer-action@v1
        with:
          command: android debug
          buildozer_version: master
