name: Build FRIDAY APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build APK with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FRIDAY_Final_Core
          path: bin/*.apk
